package App::EventStreamr::DVswitch::Sync;
use Method::Signatures;
use Moo;
use namespace::clean;

# ABSTRACT: Sync

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

Manage Sync process.

=head1 DESCRIPTION

Manage all the configured devices designated to be 
running as ingest roles.

=cut

extends 'App::EventStreamr::Sync';

1;
