package App::EventStreamr::DVswitch::Ingest::IngestTest;
use Method::Signatures;
use Moo;
use namespace::clean;

# ABSTRACT: A  Test Ingest Process

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

This Provides a Test ingest process.

=head1 DESCRIPTION

This largely extends L<App::EventStreamr::IngestTest>, for
testing for the Ingest Process.

=cut

extends 'App::EventStreamr::IngestTest';

1;
