package App::EventStreamr::Ingest;
use Method::Signatures;
use Scalar::Util::Reftype;
use Carp 'croak';
use Module::Load;
use Moo;
use namespace::clean;

# ABSTRACT: A Ingest object

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

This package provides an extendable class for starting/stopping
ingest devices.

=head1 DESCRIPTION

This package provides the core run/stop logic for Ingest Devices. A 
backend specific package will extend this and provide any extra logic 
specifc to its needs.

'backend' is expected to be overridden by the consuming role.

=cut

my $ConfigRef = sub {
  croak "config isn't a 'App::EventStreamr::Config' object!" unless reftype( $_[0] )->class eq "App::EventStreamr::Config";
};

my $StatusRef = sub {
  croak "config isn't a 'App::EventStreamr::Status' object!" unless reftype( $_[0] )->class eq "App::EventStreamr::Status";
};

has 'config'      => ( is => 'rw', required => 1, isa => $ConfigRef );
has 'status'      => ( is => 'rw', required => 1, isa => $StatusRef );
has 'backend'     => ( is => 'ro', default => sub { 'DVswitch' } );
has 'devices'     => ( is => 'ro', default => sub { { } } );

=method run_stop
  $device->run_stop()

Will start the process if it's intended to be running or stop it
if isn't.

=cut

method run_stop() {
  foreach my $device (@{$self->config->devices}) {
    if (! defined $self->devices->{$device->{id}}) {
      my $pkg = "App::EventStreamr::".$self->backend."::Ingest::$device->{type}";
      load $pkg;
      $self->devices->{$device->{id}} = $pkg->new(
        device => $device->{device},
        id => $device->{id},
        config => $self->config,
        status => $self->status,
      );
    }
    $self->devices->{$device->{id}}->run_stop();
  }
}

1;
