package App::EventStreamr::IngestTest;
use Method::Signatures;
use Moo;
use namespace::clean;

# ABSTRACT: A  Test Ingest Process

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

This Provides a Test ingest process.

=head1 DESCRIPTION

This largely extends L<App::EventStreamr::Process>, provides
default cmds that can be overidden in the configuration.

=cut

extends 'App::EventStreamr::Process';

has 'cmd'         => ( is => 'ro', lazy => 1, builder => 1 );
has 'id'          => ( is => 'ro', required => 1 );
has 'device'      => ( is => 'ro', required => 1 );
has 'type'        => ( is => 'ro', default => sub { 'IngestTest' } );

method _build_cmd() {
  return 'ping 127.0.0.1';
}

1;
