package App::EventStreamr::Process;

use v5.010;
use strict;
use warnings;
use Method::Signatures;

use Moo::Role;

# ABSTRACT: A process role

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

  This class shouldn't be directly instantiated.

=head1 DESCRIPTION

  This is a Role that can be consumed to provide process operations
  used throughout EventStreamr.

=cut

requires 'config';

1;
