package App::EventStreamr::Process;

use v5.010;
use strict;
use warnings;
use Method::Signatures; # libmethod-signatures-perl
use Proc::Daemon; # libproc-daemon-perl
use Proc::ProcessTable; # libproc-processtable-perl

use Moo::Role;

# ABSTRACT: A process role

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

  This is a role and  shouldn't be directly instantiated.

=head1 DESCRIPTION

  This is a Role that can be consumed to provide process operations
  used throughout EventStreamr.

=cut

requires 'state','command','id','config';

has 'pid' => ( is => 'rw', lazy => 1, builder => 1 );

method _build_pid() {
  my $pt = Proc::ProcessTable->new;
  my @procs = grep { $_->cmndline =~ /$self->{command}/ } @{ $pt->table };

  if (@procs) {
    $self->{state}{$self->{id}}{pid} = $procs[0]->pid;
    $self->{state}{$self->{id}}{running} = 1;
    return $self->{state}{$self->{id}}{pid};
  } else {
    $self->{state}{$self->{id}}{running} = 0;
    return 0;
  }
}

method start() {
  my %proc_opts = ( exec_command => $self->{command} );
  
  Proc::Daemon->Init( \%proc_opts );
  $self->{state}{$self->{id}}{timestamp} = time;
}

method running() {

}



1;
